### ISSUE TITLE
you can set the time to a negative number?!

### ISSUE THREAD

**Issue by YepImZynx92** [SthephanShinkufag/bytebeat-composer#11]
i just found out that you can set the time to a negative number without javascript
[image](https://i.imgur.com/tJk5NFl.png)

**Comment by SthephanShinkufag** [comment]
Its not a bug. Its an unexpected feature for advanced exploration. 😉

**Comment by YepImZynx92** [comment]
> Its not a bug. Its an unexpected feature for advanced exploration. 😉

oh, okay lmao
