### ISSUE TITLE
inefficient url storage

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#16]
in generateLocation it does
`window.location.hash = '#v3b64' + btoa(pako.deflateRaw(JSON.stringify(pData), { to: 'string' }));`
JSON.stringify isn't needed here, since pako already converts to string.
the urls generated when using stringify is longer, likely because pako compresses the datatypes in different ways.
i would recommend creating a new url version:
`window.location.hash = '#v4b64' + btoa(pako.deflateRaw(pData, { to: 'string' }));`
i don't know how loading urls works with this, it might actually be the same which if that's the case you wouldn't need the version bump

**Comment by SthephanShinkufag** [comment]
https://nodeca.github.io/pako/#deflateRaw

The input data can be Uint8Array or String, not an object.

**Comment by SArpnt** [comment]
> https://nodeca.github.io/pako/#deflateRaw
> 
> The input data can be Uint8Array or String, not an object.

i checked just now, and an object doesn't work. i wouldn't recommend using those docs as a basis though since the version of pako you're using is extremely outdated.
