### ISSUE TITLE
= isPlaying ? 'Pause' : 'Play'; is buggy

### ISSUE THREAD

**Issue by 21436587** [SthephanShinkufag/bytebeat-composer#21]
```
411	togglePlay(isPlaying, isSendData = true) {
412		this.controlTogglePlay.title = isPlaying ? 'Pause' : 'Play';  << this causes error
413		this.controlTogglePlay.classList.toggle('control-play=', !isPlaying);
```
In https://21436587.github.io/tier2_bytebeat/ , this string causes error, as
```Uncaught TypeError: Cannot set properties of null (setting 'title')```
Do my web has errors? Please let me know.

**Comment by SArpnt** [comment]
this is an issue with your website, not dollchan. you incorrectly merged commits.  
i don't think this is the place to ask for get coding advice
