### ISSUE TITLE
odd unicode in dates

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#25]
many dates seem to have unicode left-to-right mark for some reason? i assume this is a mistake
![image](https://user-images.githubusercontent.com/36542932/148606875-7a726cee-fbf8-4a72-8421-3a3e222872ad.png)

**Comment by SArpnt** [comment]
i'm finding odd unicode in other areas as well now, for example the bytebeat description has u+2122 instead of a regular dash and although technically this is the correct character to use since it's the unicode minus sign i'm not sure if this is intentional or appropriate in a programming context
![image](https://user-images.githubusercontent.com/36542932/148607393-11998e64-11dc-4347-9488-d814e7edcca6.png)

**Comment by SthephanShinkufag** [comment]
This is because of fast copying. Thanks for report!
