### ISSUE TITLE
not quite minified code in library

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#27]
i minified some of my songs even more in my fork (i overwrote the originals because I've done that multiple times before and i don't feel like keeping multiple versions of my own songs)

there's some other code in the library that can still be minified but it's something I'll work on later when the library is a bit more stable

**Comment by SthephanShinkufag** [comment]
Of course, the minified versions I presented in the updated library are not the most minified ones. We can continue to do this.
For example, in many places `pow(x,y)` can be replaced by `x**y`.

**Comment by SArpnt** [comment]
considering my bytebeats were copied over and other bytebeats would be an unrealistic effort i think it's reasonable to close this
