### ISSUE TITLE
"refeshCalc" merge issue

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#3]
`refeshCalc` was an incorrect spelling which i changed, the function name is now `refreshCalc`.
some parts of the code are still calling `refeshCalc`, which shows as errors in the console and may impact functionality

i think this function is also called unneccicarily at some points, but i'm not sure

i would reccomend looking over the code again for issues and doing some testing, the merge seems a bit rushed

**Comment by SthephanShinkufag** [comment]
Thank you for report and advice!
