### ISSUE TITLE
Scope is vertically squished before text editor

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#34]
not sure if this is a bug but i assume it's unintentional and should at least be considered
when the window is too short the scope will be shortened before the text editor is, the scope loses its aspect ratio in the process

**Comment by SthephanShinkufag** [comment]
I don't quite understand what you mean, but I don't see an issue while resizing.

![Codemirror_resize_2 gif](https://user-images.githubusercontent.com/1059874/149524976-d54cc330-8964-4c3a-825b-7d832ffd977c.gif)

**Comment by SArpnt** [comment]
that's a horizontal resize, not a vertical resize. the issue happens when the window is too short, or now that you added vertical resize to codemirror, it also happens when dragging the codemirror out to be too large.
