### ISSUE TITLE
show errors at runtime

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#36]
the code `t>>11&1?a:t` has errors due to the undefined value a, but the errors don't happen at t=0. it would be useful to see errors that happen later, especially for debugging scripts involving persistent variables.

**Comment by SthephanShinkufag** [comment]
Also, since the codemirror adds line numbering, I can add an indication of the line and the character where the error is located.

**Comment by SArpnt** [comment]
note that my fork already has a complete error system with most of the features that could be useful
