### ISSUE TITLE
Dangerous Error instance property string conversion

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#38]
```js
return `${ when } error: ${ err.message } (at line ${ err.lineNumber - 3 }, character ${ err.columnNumber })`;
```
this line implicitly converts properties of err, which can be changed
```js
(_=>{a=new Error();a.message={toString:_=>"Slammed!"};throw a})()
```
this applies to all properties being used here

**Comment by SArpnt** [comment]
not quite fixed, the numbers still aren't typechecked.
```js
(_=>{a=new Error();a.lineNumber=Symbol();throw a})()
```

**Comment by SthephanShinkufag** [comment]
> not quite fixed, the numbers still aren't typechecked.

Done.
https://github.com/SthephanShinkufag/bytebeat-composer/commit/e8df44f9c9595d28b81ef428ab945a6f64afa115#diff-1722ec8483acad66a520c3c22355ce3e0e7db7c78589a168d01d41617ddcf802R25
