### ISSUE TITLE
player sometimes bugs out and does a weird sound when you get an error while playing your formula

### ISSUE THREAD

**Issue by YepImZynx92** [SthephanShinkufag/bytebeat-composer#39]
.

**Comment by SArpnt** [comment]
this doesn't give enough information to actually fix the issue, what formula?
what do you mean "bugs out", is that just making the weird noise or is it something separate?
if it's just the noise then how do you know it's not just what the formula should be doing?

**Comment by SthephanShinkufag** [comment]
Yes, with runtime errors during playback, freezes and brakes occurred, now the problem has been fixed.
