### ISSUE TITLE
many classic songs are not 8khz

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#43]
Techno, test3, thing, thing, floppy spinner, and plenty of others are more than 8khz, but the category description says the songs are 8khz

**Comment by SthephanShinkufag** [comment]
> [Info] — about bytebeat
[Classic] — C compatible code with one variable (t)
[JS code] — compact JavaScript code
[JS big code] — big JavaScript code
[Floatbeat] — assumes output is -1.0 to 1.0
[SthephanShi] — code SthephanShi created 

> description says
Where?

**Comment by SArpnt** [comment]
sorry, i think i got some things mixed up
