### ISSUE TITLE
stereo support

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#50]
info on my implementation [here](https://github.com/SArpnt/bytebeat-composer/issues/17)

**Comment by SthephanShinkufag** [comment]
Check:

`t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6)`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSKtHSKLGzs6gBEpaaaiZmaiBenEYJiDY0BgmbaSrVAgA

`[t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6)]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSii7R0iixs7OoARKWmmomZmogXpxGCYg2NAYJm2nGKtUCAA

`[,t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6)]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSitYp0dIosbOzqAESlppqJmZqIF6cRgmINjQGCZtpxirVAgA

`[t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6),0]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSii7R0iixs7OoARKWmmomZmogXpxGCYg2NAYJm2nqGMQq1QIA

`[0,t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6)]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSijbQKdHSKLGzs6gBEpaaaiZmaiBenEYJiDY0BgmbacYq1QIA

`[t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6),t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6)]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSii7R0iixs7OoARKWmmomZmogXpxGCYg2NAYJm2nqEKMoVqkWAA

`[t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>6),t*(t>>8|t>>9)&46&t>>8^(t&t>>13|t>>3)]`
https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJSii7R0iixs7OoARKWmmomZmogXpxGCYg2NAYJm2nqEFZkrBmrVAsA
