### ISSUE TITLE
pausing and reversing doesn't reset the speed up / speed reverse count

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#52]
i assume the speed up should start at 2 and increase but it can often end up starting at 4 or 8 because the buttons were previously used

**Comment by SthephanShinkufag** [comment]
Pausing shouldn't reset fast playback in my opinion. In case I want to view the waveform by clicking on the canvas, which will cause a pause. And the second click to continue fast playback at the same speed.

**Comment by SthephanShinkufag** [comment]
But the stop should reset the fast playback.

**Comment by SArpnt** [comment]
> Pausing shouldn't reset fast playback in my opinion. In case I want to view the waveform by clicking on the canvas, which will cause a pause. And the second click to continue fast playback at the same speed.

the canvas play button and the one with the controls behave differently despite being the same icon

**Comment by SthephanShinkufag** [comment]
So if I click on pause control button then fast buttons should reset as you say. But if I click on pause in canvas, it shouldn't?

**Comment by SthephanShinkufag** [comment]
I thought about it and decided that you are right. When fast-forwarding and I want to listen normally, I stop playback with the first click on pause in the canvas, with the second click I start normal playback.
