### ISSUE TITLE
no margins/padding on text section in wide mode

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#56]
details summaries touch both the left and right side when it would likely look better with a margin

**Comment by SthephanShinkufag** [comment]
Sorry, I did not quite understand what you mean. There are already was padding at left and right, I just increase it now.
But If I turn padding to margin, there was an ugly gap in background.
![Summary_margin](https://user-images.githubusercontent.com/1059874/174413117-4cc6e9c8-ac22-4ae8-be59-7da9c4f3ed72.png)

**Comment by SArpnt** [comment]
![image](https://user-images.githubusercontent.com/36542932/174444307-60322431-e0fc-47a3-b9cd-5fa85ca6148a.png)
the summaries have a rounded border but touch the edge.
this could be solved by applying a horizontal padding or a margin to the content element

**Comment by SthephanShinkufag** [comment]
Oh, now I understand. The fact that the headera touched the edges did not hurt my eyes, it was ok for me. Also all the content and formulas is now shrinked and take up more space in height. But ok, let it be.
