### ISSUE TITLE
larger fonts

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#57]
12px is hard to read for a lot of people, i even get slowed down significantly trying to read it on my laptop. it seems to have gotten confused with the more standard font size of 12pt, which is 16px.

an ideal font size for readability would be 12pt/16px but it's probably too large considering the massive code blocks and need for more space in the programming area. the best option is probably 14px which seems to work perfectly well.

the controls especially should be changed, there's plenty of completely wasted space which could be filled by a larger font.

**Comment by SthephanShinkufag** [comment]
Increased fonts from 12px to 10.5pt (equals to 14px).
