### ISSUE TITLE
merge play buttons

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#58]
more of a suggestion, you may not want to do thi

![image](https://user-images.githubusercontent.com/36542932/174463494-77c62f61-2f4a-4a36-8f73-7221a222d164.png)
there's a bit of wasted opportunity here:
- play and reverse buttons do nothing when clicked multiple times
- fast forward and reverse buttons slow down again after some speedup

i think it would make more sense to merge the play and fast play buttons, and make it just continue to speed up infinitely with repeated clicks. there's little benefit of immediately starting at 2x speed, and it's not much of an issue to pause before resuming normal speed.

**Comment by SthephanShinkufag** [comment]
Thank you for good idea! Also infinite speed up can be dangerous at very high values, limited to 64, button just disables now.
