### ISSUE TITLE
flex-grow controls

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#59]
another suggestion that you may or may not want to implement

![image](https://user-images.githubusercontent.com/36542932/174463582-04a60e59-cc08-49a6-afa6-de2d27e1e5be.png)
by applying `flex-grow: 1` to the volume slider it grows to fill the space left in the flex area

some other things you'll need to note:
![image](https://user-images.githubusercontent.com/36542932/174463624-f5c81aaf-b923-40d1-b5ed-afbfe4dfd20e.png)
volume slider only has left margin (it doesn't match the buttons either, you'll probably want to fix this regardless of the other changes)

![image](https://user-images.githubusercontent.com/36542932/174463657-130a087e-51f4-4c9b-9a1e-64173cc49309.png)
minimum width means it wraps early and causes this, this can also happen after some more significant shrinking
upper row won't match as it also has nothing to grow inside it. you could line it up with `justify-content: space-between` and flex grow on other viable elements (note that flex grow allows you to adjust the ratios things grow relative to other things that can grow in the container)

**Comment by SthephanShinkufag** [comment]
Nice!

> justify-content: space-between

Those spaces looks ugly. Just limited volume with `max-width`.

**Comment by SArpnt** [comment]
![image](https://user-images.githubusercontent.com/36542932/175794407-00510a28-9687-4036-9ebc-dfb0e68f12bf.png)
the controls don't yet line up with the edge, this is because margins are used on the elements.
you may want to use flex-gap instead

**Comment by SArpnt** [comment]
also just note that this still happens
![image](https://user-images.githubusercontent.com/36542932/175794423-69892ce2-f283-40dd-aee8-53840fb6ab6f.png)

if both of these aren't considered issues this can be closed

**Comment by SthephanShinkufag** [comment]
> also just note that this still happens

Hmm, I don't think someone will use screens <=256px, this is the width when controls become 5 rows and more.
