### ISSUE TITLE
could you add my remix of crazy groovy beats

### ISSUE THREAD

**Issue by juanroman74454811** [SthephanShinkufag/bytebeat-composer#64]
code: a=t-2048,(t&t>>7&t*(t>>((t&633455)>>13)))+(t*t/4&t>>12&117)+(t*(a>>7&a>>8&a>>9&131)>>t/62)

**Comment by juanroman74454811** [comment]
help how do i remove an isssue

**Comment by JukoiDev** [comment]
close it
