### ISSUE TITLE
Soo, whats happening with TIRO? 

### ISSUE THREAD

**Issue by juanroman74454811** [SthephanShinkufag/bytebeat-composer#66]
I mean i kind of like TIRO, but i think this is gonna become TIRO Remix land,

**Comment by SthephanShinkufag** [comment]
I'm sorry I don't understand you.

**Comment by juanroman74454811** [comment]
i keep seeing remixes of The Time Is Running Out and its probably worrying me about this just being a complete loop,

**Comment by juanroman74454811** [comment]
heres my screenshot
![Screenshot 2022-11-03 at 11-50-24 Bytebeat composer](https://user-images.githubusercontent.com/92176733/199754118-425e3927-31ad-4d41-9d3d-25f1f58f1d84.png)
![Screenshot 2022-11-03 at 11-49-59 Bytebeat composer](https://user-images.githubusercontent.com/92176733/199754129-d5ad098b-7941-4b47-af6b-5fa0964d53f4.png)
![Screenshot 2022-11-03 at 11-48-12 Bytebeat composer](https://user-images.githubusercontent.com/92176733/199754136-09e7f813-41d1-4fb8-8bbb-13ae94204c15.png)

**Comment by SthephanShinkufag** [comment]
> being a complete loop
Still don't understand. What this means? Is something wrong?

**Comment by juanroman74454811** [comment]
uhh, yea


actually i like the TIRO remixes!
