### ISSUE TITLE
Uhh, why doesnt this work on Pale Moon?

### ISSUE THREAD

**Issue by juanroman74454811** [SthephanShinkufag/bytebeat-composer#67]
Tell me what this is, it doesnt work, i have screenshot, but its not compatible in Pale Moon,

**Comment by SthephanShinkufag** [comment]
Because old browsers and its forks doesn't support modern technologies and not compatible.

**Comment by juanroman74454811** [comment]
But, Chasyxx actually works!

**Comment by SthephanShinkufag** [comment]
By choosing to use older engines, you voluntarily refuse to support many resources that use modern ES.Next technologies such as ECMAScript 2022, ECMAScript 2021 ECMAScript 2020, etc.

> But, Chasyxx actually works!
this is a fork of ancient version of my bytebeat player a years ago, where nothing has been done yet.

**Comment by juanroman74454811** [comment]
Oh, thanks for telling me!

**Comment by juanroman74454811** [comment]
Plus i would credit to you and license! And i would make a Electron version unless you dont have internet!

**Comment by SthephanShinkufag** [comment]
I doubt you will succeed. AudioWorklet supports from Firefox 76, for example.

**Comment by juanroman74454811** [comment]
Alright thanks for telling me, im gonna go mashup some bytebeats,

**Comment by juanroman74454811** [comment]
Let me close this so i can stop getting replies or something

**Comment by juanroman74454811** [comment]
Oh wait, i already closed this, oh welp, im just gonna go out to do my normal day cycle,
