### ISSUE TITLE
Add this code 

### ISSUE THREAD

**Issue by juanroman74454811** [SthephanShinkufag/bytebeat-composer#68]
`t%((21&-622|t>>10)&42)<<2|t>>3`
This is a remix of your bytebeat,

**Comment by SthephanShinkufag** [comment]
Why do you think it is worthy to be in the library?

**Comment by juanroman74454811** [comment]
I experimented with your bytebeat i have seen and i made a remix, suprisingly it went well,
The reason why is because:
Im a wide remixer of almost any bytebeat.
I probably remixed this one because i forgot to add drums when i was making this remix,
