### ISSUE TITLE
many playlist issues

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#7]
i keep noticing a lot of playlist issues, it's difficult to remember them all but the most recent ones i've seen are with No Limit

No Limit non-sine version links to a post by ryg that uses sine and doesn't match the code, it's not clear where the code comes from. rygs username is also capitalized, which as far as i can tell is incorrect.

No Limit added recently isn't the original, it's some other modified version that still doesn't use sine, and it's not clear where this is from either.

the original No Limit and rygs optimizations are nowhere in the playlist.

i've seen many other issues, such as:
- incorrect name spelling (sinewave dubstep is spelled sinevawe dubstep)
- songs strangely left out (cool waveform i guess's original post has two different bytebeats, the playlist only has one)
- likely other things i can't even remember, the diffs between our playlists should be checked

where does the name No Limit even come from? i feel like we should have some wiki to keep track of the history of bytebeats, the pouet forms are already filled with dead links and it's not clear what information will be lost. (it would also be extremely convenient to have since the library could be generated from it)

i think at some point both of us should go through both of the playlists and try and fix everything, and add some system for leaving notes for when the history, versions, original posts, and authors of a song can't be found.

**Comment by SthephanShinkufag** [comment]
> where does the name No Limit even come from?

https://www.youtube.com/watch?v=qM5W7Xn7FiA

> No Limit added recently

Its not added recently.

https://github.com/SthephanShinkufag/bytebeat-composer/commit/85595e1598b60a392daa34bdfbaf2075b0ff6553#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R446
https://github.com/SthephanShinkufag/bytebeat-composer/commit/3ce7fccb008e12bd860f123c2a81d7e77a4d66df#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R575

I don't remember where I took these optimized veriosns. The first link code was a years ago before github repo, in my text file collection.

**Comment by SthephanShinkufag** [comment]
Also I optimized A LOT of songs. Almost 70% of songs are optimized anyway if you look closely. Removed unnecessary parentheses, and the like.
