### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by cabfile** [SthephanShinkufag/bytebeat-composer#72]
its just stuck on this
![Безымянный](https://github.com/SthephanShinkufag/bytebeat-composer/assets/32414797/cdb2676e-b936-4390-bcc0-2000a157e890)

**Comment by Maxi2022gt** [comment]
It also happened to me, but this time it says that there is an error of privacy.
I dont know if it's a GitHub Pages error, or it is that dollchan is down.

**Comment by SthephanShinkufag** [comment]
Dollchan moved to new VPS server now. Old host was weak and slow.
