### ISSUE TITLE
C compatible code not working on Code::Blocks

### ISSUE THREAD

**Issue by floppa-the-flopper** [SthephanShinkufag/bytebeat-composer#75]
When I try to play `t*(0xCA98CA98CA98>>(t>>9&44)&15)|t>>8|4E4/(t&4095)` on a C++ script, it doesn't work. Instead I get `C:\Users\PC\Downloads\gdithings-main\gditest\bytebeat.cpp|31|error: invalid operands of types 'long long int' and 'double' to binary 'operator|'|`
Also ignore the fact its in gdithings-main

**Comment by SArpnt** [comment]
what type is t? it looks like you made it a double when it should be a long long int

**Comment by floppa-the-flopper** [comment]
> what type is t? it looks like you made it a double when it should be a long long int

idk if you are asking what type t is or what type the code is

**Comment by SArpnt** [comment]
i asked "what type is t", and mentioned types of variables. i don't know what you mean by "what type the code is".

**Comment by floppa-the-flopper** [comment]
> i asked "what type is t", and mentioned types of variables. i don't know what you mean by "what type the code is".
i dont know what type t is

**Comment by floppa-the-flopper** [comment]
> i asked "what type is t", and mentioned types of variables. i don't know what you mean by "what type the code is".

i dont know what type t is

**Comment by floppa-the-flopper** [comment]
also trying to send that i forgot i was meant to use 2 newlines and i used 1 newline

**Comment by floppa-the-flopper** [comment]
xd

**Comment by SArpnt** [comment]
you should learn at least the basics how c or c++ works before trying to work with c or c++ code

**Comment by floppa-the-flopper** [comment]
i know how to use c and c++ but i dont know what type t is

**Comment by SArpnt** [comment]
if you know how to code in c or c++ that should be extremely easy to figure out. this is like saying that you know how to read a clock but don't know what hour it is

**Comment by floppa-the-flopper** [comment]
bro i dont use stuff like double and long long int alot in coding

**Comment by floppa-the-flopper** [comment]
- e

**Comment by floppa-the-flopper** [comment]
i can give you the code if you want

**Comment by floppa-the-flopper** [comment]
ok wait.
i think i can  get it

**Comment by floppa-the-flopper** [comment]
apparently its a DWORD

**Comment by floppa-the-flopper** [comment]
bro just respond

**Comment by floppa-the-flopper** [comment]
i think i got it

**Comment by SthephanShinkufag** [comment]
@floppa-the-flopper

I have `unsigned long t` in some of my projects, and had `Error: operand types 'unsigned long' and '' are incompatible with the '|' or '|=' operator`.

But if you replace `4E4` to `40000`, it would work!

`t*(0xCA98CA98CA98>>(t>>9&44)&15)|t>>8|40000/(t&4095)`

Maybe I need to replace it in the library?

**Comment by SthephanShinkufag** [comment]
The same with hydrogen fucker:
`(t/2/(4+(t>>13&3))*128|t>>(t>>12&15))+4E5/(t&4095)|t>>4` error
`(t/2/(4+(t>>13&3))*128|t>>(t>>12&15))+400000/(t&4095)|t>>4` ok

**Comment by SthephanShinkufag** [comment]
But "OUR task is infinity" by kOLbOSa_exe is ok with `4E5`, because there is no `&`
`(t>>11&t>>12)*(t>>8&t>>16)%34*t+4E5/(t&4095)` ok

**Comment by floppa-the-flopper** [comment]
> I have `unsigned long t` in some of my projects, and had `Error: operand types 'unsigned long' and '' are incompatible with the '|' or '|=' operator`.
> 
> But if replace `4E4` to `40000`, it would work!

ok

**Comment by floppa-the-flopper** [comment]
Issue closed
