### ISSUE TITLE
github version doesnt work

### ISSUE THREAD

**Issue by cabfile** [SthephanShinkufag/bytebeat-composer#77]
looking at the network tab, it seems that codemirror is not loading
![proof](https://github.com/SthephanShinkufag/bytebeat-composer/assets/32414797/5b9d8f94-2c68-4dca-82d7-c5360735c6fb)

**Comment by SthephanShinkufag** [comment]
Github version is not working. This was done on purpose. Reddit schoolchildren massively created clones of my player, without any changes, and promoted their clones for mass use. I do not like it.

**Comment by cabfile** [comment]
i was just starting to try to write a library auto-downloader :(

**Comment by SthephanShinkufag** [comment]
Now everything works, I removed the restriction.
But now you have to generate or fulfill the library yourself.

1. Setup php and mysqli on your server
2. Copy `settings.default.php` into `settings.php` with your parameters.
3. Give access to the `/data` folder.
4. Execute `bytebeat.php` then login.
5. Click the `Migrate to database` button.
6. Click the `Make .json files` button.

Will be generated  a `/data/json` folder with .json library files, and a `/data/songs` folder with .js files of songs over 1 KB.

**Comment by gfljs2100-user3** [comment]
How can I setup a php on GitHub pages?

**Comment by ameen272** [comment]
> How can I setup a php on GitHub pages?

windows, linux or phone?

**Comment by gfljs2100-user3** [comment]
> > How can I setup a php on GitHub pages?
> 
> windows, linux or phone?

I’m on tablet

**Comment by gfljs2100-user3** [comment]
> 2. Copy `settings.default.php` into `settings.php` with your parameters.
How can I copy settings.default.php into settings.php?
