### ISSUE TITLE
Funcbeat samplerate can be undefined at t=0

### ISSUE THREAD

**Issue by Chasyxx** [SthephanShinkufag/bytebeat-composer#79]
Discovered this while working on THE[BOX]'s funcbeat cover. Sometimes funebeat's samplerate value can be undefined at t=0, which threw off the snare on my cover, including compilation and page load.
https://dollchan.net/bytebeat/#v3b64PY7BCsIwEER/ZVkQklqwlSKi9OoHmGsusdlioN1IuqWH0n83ojjHGXjzVuyiJ7xgIpkTQz9zJyGyktJoWC1bCb0ybTuzpz4weQ3yTHEBiwYWN8F/yA3sIbCo5NjHUeni1OgPgYaJ4HcgB1PUx3OVs6uvljcscXLja6C7kyzSNHVVlTh+rW5Z50FOcHsD

(edit: changed the link to be a bit more dynamic to samplerate and show that this does happen more than once)

**Comment by Chasyxx** [comment]
Turns out it also happens on Sarpnt's original player: https://bytebeat.ficial.net/#5X6AAD8K0otKS3KU0grzUsuyczP0yjRCdZUqObizEzTCLa1Lc1LSU3LzEtN0VQoySjKL1dQClYoTyxWgIsrKCloK2TmlWgUJeal5OdqaGqZmWhycabmFKcqQI0u0Q/WMjSyMAACVUNrrloA

**Comment by SthephanShinkufag** [comment]
Thanks for pointing out the error!
