### ISSUE TITLE
add jsfuck support

### ISSUE THREAD

**Issue by codermannnnnnn** [SthephanShinkufag/bytebeat-composer#84]
using jsfuck code for "t" it gives an error saying t is not defined, i have no more information that i can think of to put here

**Comment by jan-ale** [comment]
jsfuck tries to execute code outside of any other code, so it can't get t. specifically, it is in the scope of window. fun fact: this was a problem in html5bytebeat: it executed outside of the security code! to solve the problem, you can uncheck "eval source" and put it inside eval(). that compiles the code every frame. [a faster version that only compiles once](https://dollchan.net/bytebeat/#v3b64FcxBCoMwEADArywLShIUtXgSq7e+IpcQt5hWYkk2epD+XT0PzIF2nQg75LHuzPOVvGW3eqGRNRYaA3EKHkT7yHkYmlpmTasuqlRfQqDfYiwBzy7C7niGT3wn+wXy9zrBRiFem6pkYQRL/J8)
