### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by tema5002** [SthephanShinkufag/bytebeat-composer#87]
When I change the playback speed of a song in the player and then open a different song, it incorrectly displays "2 >" as the speed. The actual playback speed is from the previous song.
Steps to Reproduce:
1. Open any bytebeat song in the library.
2. Change the playback speed.
3. Choose another bytebeat song.

https://github.com/user-attachments/assets/a1d35d3b-aff7-4aee-a848-d413e038cbf0

**Comment by SthephanShinkufag** [comment]
Now the speed resets to normal.

**Comment by SthephanShinkufag** [comment]
Oh, forget to update the dollchan site. I'll come home and update  in a couple of hours.

**Comment by SthephanShinkufag** [comment]
Updated.
